name: Reformatting & Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache pre-commit paths
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/pip
            $RUNNER_TOOL_CACHE/Python/*
            ~/.cache/pre-commit
          key: ${{ runner.os }}-build-${{ matrix.python-version }}-${{
            hashFiles('.pre-commit-config.yaml') }}

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install-pre-commit
        run: python -m pip install --upgrade pre-commit

      - name: Run Pre-commit
        run: pre-commit run --all-files || (exit 0)
